#ifndef ENUMFUNCTIONS_H
#define ENUMFUNCTION_H

enum class Functions {
	DISPLAY_ALL_COMBINATIONS = 1,
	DISPLAY_FIRST_COMBINATION_OF_EVERY_PERMUTATION =2,
	DISPLAY_FIRST_POSSIBLE_COMBINATION =3,
	MAX_FUNCTION,
};

#endif